# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: "- groups:\n- system:masters\nrolearn: arn:aws:iam::979310601112:role/UdacityFlaskDeployCBKubectlRole\nusername:
    build \n- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::979310601112:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1AK2QYSELRXVJ\n
    \ username: system:node:{{EC2PrivateDNSName}}\n"
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-11T06:17:07Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2325"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 26f82794-c739-442f-b83d-f97456c01a61
